"""Initial migration

Revision ID: 8c90a199ded2
Revises: 
Create Date: 2026-06-19 10:45:30.737463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c90a199ded2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscription',
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('billets', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['matricule'], ['inscription.matricule'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipe')
    op.drop_table('inscription')
    # ### end Alembic commands ###
